name: Go

on:
  push:
    branches: [ master ]

jobs:
  Windows:
    name: Windows
    runs-on: windows-2016
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Download modules
        run: go mod download
      - name: Build
        env:
          GOOS: windows
          GOPROXY: "https://proxy.golang.org"
          GO111MODULE: on
        run: go build .
      - name: Test
        run: go test -v .
  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go
      - name: Installing 
        run: sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev gir1.2-appindicator3-0.1
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Download modules
        run: go mod download
      - name: Build
        env:
          GOOS: linux
          GOPROXY: "https://proxy.golang.org"
        run: go build .
      - name: Test
        run: go test -v .
