name: Go

on:
  push:
    branches: [ master ]

jobs:
  Windows:
    name: Windows
    runs-on: windows-2016
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Build
        env:
          GOOS: windows
          GOPROXY: "https://proxy.golang.org"
          GO111MODULE: on
        run: go build .
      - name: Test
        run: go test -v .
  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
          GO111MODULE: on
        run: go build .
      - name: Test
        run: go test -v .