name: Linux

on:
  push:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          go install golang.org/x/lint/golint
          make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Updating packages
        run: sudo apt-get update

      - name: Installing new packages
        run: sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev gir1.2-appindicator3-0.1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download modules
        run: go mod download

      - name: Run Unit tests.
        run: make test

      #- name: Run Unit tests.
      #  run: make test-coverage

      #- name: Upload Coverage report to CodeCov
      #  uses: codecov/codecov-action@v1.0.0
      #  with:
      #    token: ${{secrets.CODECOV_TOKEN}}
      #    file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Updating packages
        run: sudo apt-get update

      - name: Installing new packages
        run: sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev gir1.2-appindicator3-0.1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download modules
        run: go mod download

      - name: Build
        run: make build
