name: Macos

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Download modules
        run: go mod download

      - name: Run Unit tests.
        run: go test -v .

  build:
    name: Build
    runs-on: macos-latest
    needs: [test]
    steps:
      - name: Set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Download modules
        run: go mod download

      - name: Build
        env:
          GOPROXY: https://proxy.golang.org
          GO111MODULE: on
        run: go build .
